import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";

export const FAQSection = () => {
  return (
    <section id="faq" className="py-20 bg-background">
      <div className="container px-4 md:px-6 mx-auto">
        <div className="text-center">
          <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Frequently Asked Questions</h2>
          <p className="mx-auto max-w-[700px] text-muted-foreground md:text-xl/relaxed mt-4">
            Got questions about ForumScout? We've got answers to help you understand our service better.
          </p>
        </div>
        <Accordion type="single" collapsible className="w-full max-w-[800px] mx-auto">
          <AccordionItem value="item-1">
            <AccordionTrigger>How does ForumScout monitor forums?</AccordionTrigger>
            <AccordionContent>
              ForumScout uses advanced web scraping and API integrations to monitor forums in real-time. We track new posts, unanswered questions, and trending topics to provide you with comprehensive insights.
            </AccordionContent>
          </AccordionItem>
          <AccordionItem value="item-2">
            <AccordionTrigger>What type of notifications can I receive?</AccordionTrigger>
            <AccordionContent>
              You can receive notifications via email, Slack, or Microsoft Teams. We'll alert you about unanswered questions, critical issues, and important updates based on your preferences.
            </AccordionContent>
          </AccordionItem>
          <AccordionItem value="item-3">
            <AccordionTrigger>Can I customize the reports generated by ForumScout?</AccordionTrigger>
            <AccordionContent>
              Yes, ForumScout allows you to customize reports to focus on specific metrics and timeframes. You can also export reports in various formats for further analysis and sharing.
            </AccordionContent>
          </AccordionItem>
          <AccordionItem value="item-4">
            <AccordionTrigger>Is ForumScout suitable for small and large forums?</AccordionTrigger>
            <AccordionContent>
              Absolutely! ForumScout is designed to scale with your needs, whether you're managing a small community forum or a large enterprise platform. Our flexible pricing plans cater to different forum sizes and requirements.
            </AccordionContent>
          </AccordionItem>
          <AccordionItem value="item-5">
            <AccordionTrigger>How secure is my forum data with ForumScout?</AccordionTrigger>
            <AccordionContent>
              We take data security seriously. ForumScout employs industry-standard encryption and security protocols to protect your forum data. We also comply with privacy regulations to ensure your information is safe and secure.
            </AccordionContent>
          </AccordionItem>
        </Accordion>
      </div>
    </section>
  );
}; 