import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";

export const FAQSection = () => {
  return (
    <section id="faq" className="py-20 bg-background">
      <div className="container px-4 md:px-6 mx-auto">
        <div className="text-center max-w-[800px] mx-auto mb-12">
          <div className="inline-block px-3 py-1 rounded-full bg-primary/10 text-primary text-sm font-medium mb-3">
            FAQ
          </div>
          <h2 className="text-3xl md:text-4xl font-bold tracking-tighter">
            Frequently Asked Questions
          </h2>
          <p className="text-muted-foreground md:text-lg mt-4">
            Got questions about Threadwise? We've got answers to help you understand our service better.
          </p>
        </div>
        <Accordion type="single" collapsible className="w-full max-w-[800px] mx-auto">
          <AccordionItem value="question-1">
            <AccordionTrigger>How does Threadwise monitor forums?</AccordionTrigger>
            <AccordionContent>
              Threadwise uses advanced web scraping and API integrations to monitor forums in real-time. We track new posts, unanswered questions, and trending topics to provide you with comprehensive insights.
            </AccordionContent>
          </AccordionItem>
          <AccordionItem value="question-2">
            <AccordionTrigger>What type of notifications can I receive?</AccordionTrigger>
            <AccordionContent>
              You can receive notifications via email, Slack, or Microsoft Teams. We'll alert you about unanswered questions, critical issues, and important updates based on your preferences.
            </AccordionContent>
          </AccordionItem>
          <AccordionItem value="question-3">
            <AccordionTrigger>Can I customize the reports generated by Threadwise?</AccordionTrigger>
            <AccordionContent>
              Yes, Threadwise allows you to customize reports to focus on specific metrics and timeframes. You can also export reports in various formats for further analysis and sharing.
            </AccordionContent>
          </AccordionItem>
          <AccordionItem value="question-4">
            <AccordionTrigger>Is Threadwise suitable for small and large forums?</AccordionTrigger>
            <AccordionContent>
              Absolutely! Threadwise is designed to scale with your needs, whether you're managing a small community forum or a large enterprise platform. Our flexible pricing plans cater to different forum sizes and requirements.
            </AccordionContent>
          </AccordionItem>
          <AccordionItem value="question-5">
            <AccordionTrigger>How secure is my forum data with Threadwise?</AccordionTrigger>
            <AccordionContent>
              We take data security seriously. Threadwise employs industry-standard encryption and security protocols to protect your forum data. We also comply with privacy regulations to ensure your information is safe and secure.
            </AccordionContent>
          </AccordionItem>
        </Accordion>
      </div>
    </section>
  );
}; 